{% set version = "0.9.21" %}

package:
  name: vlfeat
  version: {{ version }}

source:
  fn: vlfeat-{{ version }}-bin.tar.gz
  url: http://www.vlfeat.org/download/vlfeat-{{ version }}-bin.tar.gz
  sha1: 466e345b8f6b69a4465ada0994d945da79785c3e

  patches:
    - no_crt_copy.patch  # [win]
    - no_dll_ldflags.patch
    - no_memcpy_version_check.patch  # [linux and aarch64]

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:

test:
  requires:
    - python  # [win]

  commands:
    - sift -h
    - mser -h
    - aib -h
    - if not exist %PREFIX%\\Library\\bin\\vl.dll exit 1  # [win]
    - test -f $PREFIX/lib/libvl${SHLIB_EXT}  # [unix]

about:
  home: http://www.vlfeat.org/
  summary: The VLFeat open source library implements popular computer vision algorithms specializing in image understanding and local features extraction and matching.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - patricksnape
    - 183amir
    - Tobias-Fischer
