{% set version = "0.9.21" %}

package:
  name: vlfeat
  version: {{ version }}

source:
  fn: vlfeat-{{ version }}-bin.tar.gz
  url: http://www.vlfeat.org/download/vlfeat-{{ version }}-bin.tar.gz
  sha1: 466e345b8f6b69a4465ada0994d945da79785c3e

  patches:
    - no_crt_copy.patch  # [win]
    - no_snprintf.patch  # [win and vc==14]
    - vs2010_openmp.patch  # [win and py34]
    - vs2010_path.patch  # [win64 and py34]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}

test:
  requires:
    - python  # [win]

  commands:
    - sift -h
    - mser -h
    - aib -h
    - if not exist %PREFIX%\\Library\\bin\\vl.dll exit 1  # [win]
    - test -f $PREFIX/lib/libvl.dylib  # [osx]
    - test -f $PREFIX/lib/libvl.so  # [linux]

about:
  home: http://www.vlfeat.org/
  summary: The VLFeat open source library implements popular computer vision algorithms specializing in image understanding and local features extraction and matching.
  license: BSD 2-Clause

extra:
  recipe-maintainers:
    - patricksnape
    - 183amir
