compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_aarch64
provider:
  linux_aarch64: default
conda_build:
  pkg_format: '2'
test: native_and_emulated
